package llm

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	personapkg "github.com/jdonohoo/legal-bot/go/internal/persona"
)

const (
	ExitTimeout = 124 // GNU timeout convention
)

// RunOptions configures an LLM subprocess invocation.
type RunOptions struct {
	Ctx           context.Context // optional parent context for cancellation
	LLM           string          // claude, codex, gemini, copilot
	Model         string          // optional model string passed through to the engine
	Effort        string          // optional reasoning/effort value when supported
	Prompt        string
	OutputFile    string // optional: write output to this file
	Persona       string // optional: persona context to inject
	Timeout       time.Duration
	WorkingDir    string // working directory for the LLM subprocess
	AgentsDir     string // path to agents/ for persona loading
	AllowFileRead bool   // when true, permit the LLM to read files from the filesystem
	QuietStderr   bool   // when true, discard stderr (TUI mode - prevents display corruption)
}

// Result holds the output of an LLM run.
type Result struct {
	Output     string
	Stderr     string // last 2KB of subprocess stderr
	ExitCode   int
	TimedOut   bool
	LLMUsed    string
	ModelUsed  string
	EffortUsed string
	Duration   time.Duration
}

// Run spawns an LLM subprocess with timeout and process group management.
func Run(opts RunOptions) (*Result, error) {
	if opts.Timeout == 0 {
		opts.Timeout = 20 * time.Minute
	}

	// Resolve LLM and check availability, fall back to claude
	llmRequested := opts.LLM
	llm := resolveLLM(opts.LLM)

	// Build persona context
	personaContext := ""
	if opts.Persona != "" && opts.AgentsDir != "" {
		personaContext = loadPersonaContext(opts.AgentsDir, opts.Persona)
	}

	// Text-only directive for claude/gemini
	var textOnly string
	if opts.AllowFileRead {
		textOnly = "IMPORTANT: You MAY read files from the filesystem to gather information. Output your complete analysis as plain text to stdout. Do NOT create, write, or modify any files.\n\n"
	} else {
		textOnly = "IMPORTANT: Output your complete analysis as plain text to stdout. Do NOT create, write, or modify any files. Do NOT use any file-writing tools. Just output your analysis directly as text.\n\n"
	}

	// Sign-off suffix
	var signOff string
	signOff = "\n\n---\n> This output was generated by Legal-Bot. It is AI-generated legal analysis and strategy support. Verify it against source documents before filing, serving, sending, or relying on it externally."

	parent := opts.Ctx
	if parent == nil {
		parent = context.Background()
	}
	ctx, cancel := context.WithTimeout(parent, opts.Timeout)
	defer cancel()

	start := time.Now()

	var cmd *exec.Cmd
	var commandPath string
	var commandArgs []string
	var output []byte
	var err error

	switch llm {
	case "claude":
		fullPrompt := textOnly + personaContext + opts.Prompt + signOff
		commandPath = "claude"
		commandArgs = buildClaudeArgs(fullPrompt, opts)
		cmd = exec.CommandContext(ctx, commandPath, commandArgs...)
		cmd.Env = append(os.Environ(), "NODE_OPTIONS=--max-old-space-size=32768")

	case "codex":
		codexPrefix := "IMPORTANT: You are acting as an ANALYSIS agent. Write your complete analysis as a detailed markdown document. Do NOT create any code files or project scaffolding. Output your analysis directly as text.\n\n"
		fullPrompt := codexPrefix + personaContext + opts.Prompt + signOff

		tmpFile, tmpErr := os.CreateTemp("", "legal-bot-codex.*.md")
		if tmpErr != nil {
			return nil, fmt.Errorf("create temp file for codex: %w", tmpErr)
		}
		tmpPath := tmpFile.Name()
		tmpFile.Close()
		defer os.Remove(tmpPath)

		codexDir := opts.WorkingDir
		if codexDir == "" {
			codexDir = "."
		}

		codexExe, resolveErr := resolveCodexExecutable()
		if resolveErr != nil {
			return nil, fmt.Errorf("resolve codex executable: %w", resolveErr)
		}
		commandPath = codexExe
		commandArgs = buildCodexArgs(tmpPath, codexDir, opts)
		cmd = exec.CommandContext(ctx, commandPath, commandArgs...)
		// Codex writes the last assistant message to tmpPath. Feed the full
		// prompt over stdin so large intake/workflow prompts do not exceed the
		// Windows command-line length limit when codex is installed via npm.
		cmd.Stdin = strings.NewReader(fullPrompt)

		// Set process group so we can kill children
		setProcGroup(cmd)
		var stdoutBuf bytes.Buffer
		cmd.Stdout = &stdoutBuf
		var stderrBuf bytes.Buffer
		if opts.QuietStderr {
			cmd.Stderr = &stderrBuf
		} else {
			cmd.Stderr = io.MultiWriter(os.Stderr, &stderrBuf)
		}

		runErr := cmd.Run()
		duration := time.Since(start)

		exitCode := exitCodeFromErr(runErr)
		timedOut := ctx.Err() == context.DeadlineExceeded
		if timedOut {
			killProcessGroup(cmd)
			exitCode = ExitTimeout
			fmt.Fprintf(os.Stderr, "[legal-bot] Timeout: codex exceeded %s limit\n", opts.Timeout)
		}

		// Read codex output
		data, _ := os.ReadFile(tmpPath)
		outputStr := string(data)

		result := &Result{
			Output:     outputStr,
			Stderr:     truncStderr(stderrBuf.String(), 2048),
			ExitCode:   exitCode,
			TimedOut:   timedOut,
			LLMUsed:    llm,
			ModelUsed:  opts.Model,
			EffortUsed: effectiveEffort(llm, opts.Effort),
			Duration:   duration,
		}

		emitRunDiagnostics(llm, opts, commandPath, commandArgs, stdoutBuf.Len(), result, runErr)
		result, wErr := writeOutput(result, opts.OutputFile)
		logRun(opts, llmRequested, result, runErr, wErr)
		return result, wErr

	case "gemini":
		fullPrompt := textOnly + personaContext + opts.Prompt + signOff
		commandPath = "gemini"
		commandArgs = buildGeminiArgs(fullPrompt, opts)
		cmd = exec.CommandContext(ctx, commandPath, commandArgs...)

	case "copilot":
		fullPrompt := textOnly + personaContext + opts.Prompt + signOff
		commandPath = "copilot"
		commandArgs = buildCopilotArgs(fullPrompt, opts)
		cmd = exec.CommandContext(ctx, commandPath, commandArgs...)

	default:
		return nil, fmt.Errorf("unknown LLM: %s (valid: claude, codex, gemini, copilot)", llm)
	}

	if commandPath == "" {
		commandPath = cmd.Path
	}
	if len(commandArgs) == 0 {
		commandArgs = cmd.Args[1:]
	}

	// Set working directory so the LLM can access files there (e.g. Gemini sandbox)
	if opts.WorkingDir != "" {
		cmd.Dir = opts.WorkingDir
	}

	// Capture stdout only - let stderr pass through to the terminal so the user
	// sees progress/errors but they don't pollute the captured output.
	var stdoutBuf bytes.Buffer
	var stderrBuf bytes.Buffer
	cmd.Stdout = &stdoutBuf
	if opts.QuietStderr {
		cmd.Stderr = &stderrBuf
	} else {
		cmd.Stderr = io.MultiWriter(os.Stderr, &stderrBuf)
	}

	// Set process group for non-codex LLMs
	setProcGroup(cmd)

	err = cmd.Run()
	output = stdoutBuf.Bytes()
	duration := time.Since(start)

	exitCode := exitCodeFromErr(err)
	timedOut := ctx.Err() == context.DeadlineExceeded
	if timedOut {
		killProcessGroup(cmd)
		exitCode = ExitTimeout
		fmt.Fprintf(os.Stderr, "[legal-bot-run] Timeout: %s exceeded %s limit\n", llm, opts.Timeout)
	}

	result := &Result{
		Output:     string(output),
		Stderr:     truncStderr(stderrBuf.String(), 2048),
		ExitCode:   exitCode,
		TimedOut:   timedOut,
		LLMUsed:    llm,
		ModelUsed:  opts.Model,
		EffortUsed: effectiveEffort(llm, opts.Effort),
		Duration:   duration,
	}

	emitRunDiagnostics(llm, opts, commandPath, commandArgs, len(output), result, err)
	result, wErr := writeOutput(result, opts.OutputFile)
	logRun(opts, llmRequested, result, err, wErr)
	return result, wErr
}

func buildClaudeArgs(prompt string, opts RunOptions) []string {
	args := []string{"--dangerously-skip-permissions"}
	if opts.Model != "" {
		args = append(args, "--model", opts.Model)
	}
	if effort := effectiveEffort("claude", opts.Effort); effort != "" {
		args = append(args, "--effort", effort)
	}
	args = append(args, "-p", prompt)
	return args
}

func buildCodexArgs(outputPath string, workingDir string, opts RunOptions) []string {
	args := []string{"exec", "--skip-git-repo-check"}
	if workingDir != "" {
		args = append(args, "--cd", workingDir)
	}
	if opts.Model != "" {
		args = append(args, "--model", opts.Model)
	}
	if effort := effectiveEffort("codex", opts.Effort); effort != "" {
		args = append(args, "-c", "model_reasoning_effort="+effort)
	}
	args = append(args, "-o", outputPath)
	return args
}

func buildGeminiArgs(prompt string, opts RunOptions) []string {
	args := []string{"--yolo"}
	if opts.Model != "" {
		args = append(args, "--model", opts.Model)
	}
	args = append(args, prompt)
	return args
}

func buildCopilotArgs(prompt string, opts RunOptions) []string {
	args := []string{}
	if opts.Model != "" {
		args = append(args, "--model", opts.Model)
	}
	args = append(args, "--prompt", prompt)
	return args
}

func effectiveEffort(engine string, effort string) string {
	effort = strings.ToLower(strings.TrimSpace(effort))
	if effort == "" {
		return ""
	}
	switch engine {
	case "claude", "codex":
		return effort
	default:
		return ""
	}
}

// resolveLLM normalizes LLM names and falls back to claude if unavailable.
func resolveLLM(llm string) string {
	switch strings.ToLower(llm) {
	case "claude", "c":
		return "claude"
	case "codex", "x":
		if _, err := resolveCodexExecutable(); err != nil {
			fmt.Fprintf(os.Stderr, "[legal-bot-run] Warning: codex CLI not found, falling back to claude\n")
			return "claude"
		}
		return "codex"
	case "gemini", "g":
		if _, err := exec.LookPath("gemini"); err != nil {
			fmt.Fprintf(os.Stderr, "[legal-bot-run] Warning: gemini CLI not found, falling back to claude\n")
			return "claude"
		}
		return "gemini"
	case "copilot", "p":
		if _, err := exec.LookPath("copilot"); err != nil {
			fmt.Fprintf(os.Stderr, "[legal-bot-run] Warning: copilot CLI not found, falling back to claude\n")
			return "claude"
		}
		return "copilot"
	default:
		return llm
	}
}

func loadPersonaContext(agentsDir, persona string) string {
	persona = personapkg.ResolveName(persona)
	path := agentsDir + "/" + persona + ".md"
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	// Strip YAML frontmatter (between first two --- lines)
	content := string(data)
	lines := strings.SplitN(content, "\n", -1)
	dashCount := 0
	bodyStartLine := 0
	for i, line := range lines {
		if strings.TrimSpace(line) == "---" {
			dashCount++
			if dashCount >= 2 {
				bodyStartLine = i + 1
				break
			}
		}
	}

	if dashCount >= 2 && bodyStartLine < len(lines) {
		body := strings.Join(lines[bodyStartLine:], "\n")
		body = strings.TrimSpace(body)
		if body != "" {
			return "=== PERSONA ===\n" + body + "\n=== END PERSONA ===\n\n"
		}
	}

	return ""
}

func exitCodeFromErr(err error) int {
	if err == nil {
		return 0
	}
	if exitErr, ok := err.(*exec.ExitError); ok {
		return exitErr.ExitCode()
	}
	return 1
}

// truncStderr trims stderr to the last max bytes, strips leading blank lines
// and non-printable characters.
func truncStderr(s string, max int) string {
	if s == "" {
		return ""
	}
	// Strip non-printable chars (keep tabs and newlines)
	cleaned := strings.Map(func(r rune) rune {
		if r == '\t' || r == '\n' || r == '\r' {
			return r
		}
		if r < 32 {
			return -1
		}
		return r
	}, s)
	// Keep last max bytes
	if len(cleaned) > max {
		cleaned = cleaned[len(cleaned)-max:]
	}
	// Strip leading blank lines
	cleaned = strings.TrimLeft(cleaned, "\n\r")
	return strings.TrimSpace(cleaned)
}

// FirstLine returns the first non-empty line of s, or empty string.
func FirstLine(s string) string {
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			return line
		}
	}
	return ""
}

func writeOutput(result *Result, outputFile string) (*Result, error) {
	if result.Output == "" {
		fmt.Fprintf(os.Stderr, "[legal-bot-run] Warning: LLM produced empty output (exit code: %d)\n", result.ExitCode)
	}

	if outputFile != "" {
		if result.Output != "" {
			if err := os.WriteFile(outputFile, []byte(result.Output), 0644); err != nil {
				return result, fmt.Errorf("write output file: %w", err)
			}
		} else {
			// Write empty file so downstream knows the step ran
			if err := os.WriteFile(outputFile, nil, 0644); err != nil {
				return result, fmt.Errorf("write empty output file: %w", err)
			}
		}
	}

	return result, nil
}

func resolveCodexExecutable() (string, error) {
	if runtime.GOOS == "windows" {
		for _, candidate := range []string{"codex.cmd", "codex.exe", "codex"} {
			if path, err := exec.LookPath(candidate); err == nil {
				return path, nil
			}
		}
	}
	return exec.LookPath("codex")
}

func emitRunDiagnostics(engine string, opts RunOptions, executable string, args []string, stdoutBytes int, result *Result, runErr error) {
	if result == nil {
		return
	}
	if result.ExitCode == 0 && strings.TrimSpace(result.Output) != "" {
		return
	}
	fmt.Fprintln(os.Stderr, formatRunDiagnostic(engine, opts, executable, args, stdoutBytes, result, runErr))
}

func formatRunDiagnostic(engine string, opts RunOptions, executable string, args []string, stdoutBytes int, result *Result, runErr error) string {
	parts := []string{
		"[legal-bot-run] Diagnostic:",
		fmt.Sprintf("engine=%s", engine),
		fmt.Sprintf("model=%s", blankIfEmpty(opts.Model)),
		fmt.Sprintf("effort=%s", blankIfEmpty(effectiveEffort(engine, opts.Effort))),
		fmt.Sprintf("command=%s", commandSummary(executable, sanitizeArgsForLog(args))),
		fmt.Sprintf("exit_code=%d", result.ExitCode),
		fmt.Sprintf("stdout_bytes=%d", stdoutBytes),
		fmt.Sprintf("output_bytes=%d", len(result.Output)),
	}
	if result.TimedOut {
		parts = append(parts, "timed_out=true")
	}
	if stderr := strings.TrimSpace(result.Stderr); stderr != "" {
		parts = append(parts, fmt.Sprintf("stderr_tail=%q", truncatePrompt(stderr, 300)))
	} else if runErr != nil {
		parts = append(parts, fmt.Sprintf("error=%q", truncatePrompt(runErr.Error(), 300)))
	}
	return strings.Join(parts, " ")
}

func commandSummary(executable string, args []string) string {
	base := executable
	if executable != "" {
		base = filepath.Base(executable)
	}
	if len(args) == 0 {
		return base
	}
	return base + " " + strings.Join(args, " ")
}

func sanitizeArgsForLog(args []string) []string {
	if len(args) == 0 {
		return nil
	}
	sanitized := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		arg := args[i]
		sanitized = append(sanitized, arg)
		switch arg {
		case "-p", "--prompt", "-o", "--output-last-message", "--output-schema", "--model", "--cd", "-C":
			if i+1 < len(args) {
				replacement := "<value>"
				if arg == "-p" || arg == "--prompt" {
					replacement = "<prompt>"
				}
				sanitized = append(sanitized, replacement)
				i++
			}
		case "-c", "--config":
			if i+1 < len(args) {
				sanitized = append(sanitized, args[i+1])
				i++
			}
		default:
			if i == len(args)-1 && !strings.HasPrefix(arg, "-") {
				sanitized[len(sanitized)-1] = "<prompt>"
			}
		}
	}
	return sanitized
}

func blankIfEmpty(value string) string {
	if strings.TrimSpace(value) == "" {
		return "-"
	}
	return value
}
